version: "3.3"

networks:

  default:
    driver: bridge

services:

  postgres:
    image: postgres:15.4-bullseye
    restart: always
    environment:
      - POSTGRES_USER=charles
      - POSTGRES_PASSWORD=Guide147
      - POSTGRES_DB=schools
    ports:
      - 5432:5432
    networks:
      - default

  my_image:
    image: gitauwairimu/cmd-python-app
    depends_on:
      - postgres
    networks:
      - default