apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  host: ZGV2ZWxvcGVycHJpbnRfcHJvZ3JhbW1pbmctY2xvdWRmbGFyZS1lZHUtY29udGFjdA==  # base64-encoded host
  port: NTUzNjE=  # base64-encoded port
  database: ZGV2ZWxvcGVycHJpbnQ=  # base64-encoded database name
  user: cHJvZ3JhbW1pbmdjaGFuZ2U=  # base64-encoded user
  password: cXdlcnR5c3R5c3R5c3R5  # base64-encoded password
  SLACK_WEBHOOK_URL: QUFaemFvO...  # base64-encoded value of "AC6b96"
  ACCOUNT_SID: QUFaemFvO...  # base64-encoded value of "AC6b96af4ceebfef859e74bd30f48de009"
  AUTH_TOKEN: Ym9vdHN0cmFw...  # base64-encoded value of "b3580b05b6732db1f472a9a2f80eaea0"

