---
- hosts: dockerpostgres
  become: yes
  
  tasks:

    - name: Give executable permissions to prep.sh
      file:
        path: /prep.sh
        state: file
        owner: root
        group: root
        mode: '0755'

    - name: Run prep.sh
      shell: /prep.sh

    - name: Remove apt lock file
      file:
        state: absent
        path: "/var/lib/apt/lists/*"
    - ansible.builtin.apt:
        clean: yes
      become: yes

    - name: Update the operating system
      apt:
        update_cache: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present


    # - name: Run docker-compose up
    #   docker_compose:
    #     project_name: my_project
    #     command: up -d
