---
- hosts: dockerpostgres
  become: yes
  
  tasks:
    - name: Remove apt lock file
      file:
        state: absent
        path: "/var/lib/apt/lists/*"
    - name: Update the operating system
      apt:
        update_cache: yes

    # - name: Install Docker Compose
    #   apt:
    #     name: docker-compose
    #     state: present

    # - name: Copy docker-compose file
    #   copy:
    #     source: /ansible/run-app-docker-compose.yml
    #     dest: /ansible/run-app-docker-compose.yml
    #     mode: 0644

    # - name: Run docker-compose up
    #   docker_compose:
    #     project_name: my_project
    #     command: up -d
