---
- hosts: dockerpostgres
  become: yes
  
  tasks:

    - name: Give executable permissions to prep.sh
      file:
        path: /home/ubuntu/prep.sh
        state: file
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Run prep.sh
      shell: /home/ubuntu/prep.sh


    - name: Update the operating system
      apt:
        update_cache: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present


    - name: Run docker-compose up
      docker_compose:
        project_name: my_project
        command: up -d
